from linkerology_multitask.ml_training.MultitaskTrainerBinary import MultitaskTrainerBinary
from linkerology_multitask.ml_training.MultitaskTrainerReg import MultitaskTrainerReg
from linkerology_multitask.ml_training.SingleTargetTrainer import SingleTargetTrainer
