from linkerology_multitask.ml_models.BinaryMultitask import BinaryMultitask
from linkerology_multitask.ml_models.MulticlassMultitask import MulticlassMultitask
from linkerology_multitask.ml_models.RegMultitask import RegMultitask
